name: build pycddlib wheels

on:
  workflow_dispatch:

env:
  VCPKG_HASH: "d2ab3ed75fdf7027d6c59b493669326017540425"
  # UV_SYSTEM_PYTHON: 1

jobs:
  build_pycddlib:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install 3.12

      # clone the pycddlib repo and checkout 3.0.2
      - name: Clone pycddlib repo
        run: git clone https://github.com/mcmtroffaes/pycddlib.git

      - name: Checkout pycddlib 3.0.2
        run: cd pycddlib && git checkout 3.0.2

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libcdd-dev libgmp-dev

      - name: Build wheel (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: uv build --wheel

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install cddlib gmp

      - name: Build wheel (macOS)
        if: matrix.os == 'macos-latest'
        run: env "CFLAGS=-I$(brew --prefix)/include -L$(brew --prefix)/lib" uv build --wheel

      # - name: Install dependencies (Windows)
      #   if: matrix.os == 'windows-latest'
      #   run: choco install cddlib gmp

      # - name: Build wheel (Windows)
      #   if: matrix.os == 'windows-latest'
      #   run: uv build --wheel

      # TODO: upload wheel
